name: TradeSystem
version: ${project.version}
main: de.kevtv.kevin.minecraft_spigot_trade_system.Main
api-version: 1.13
authors: [KevTVKevin]
description: Ein TradeSystem für Minecraft Spigot 1.14
website: https://KevTV.de

commands:
  trade:
    description: /trade <Spielername>
  tradeAccept:
    description: /tradeaccept <Spielername>

permissions:
  trade.*:
    default: op
    children:
      trade.trade: true
      trade.accept: true
  trade.trade:
    default: notop
  trade.accept:
    default: notop